# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_source_group1
        }
    }
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/HubAccount.cpp) \
        $$quote($$BASEDIR/src/HubCache.cpp) \
        $$quote($$BASEDIR/src/TestAccount.cpp) \
        $$quote($$BASEDIR/src/UDSUtil.cpp) \
        $$quote($$BASEDIR/src/Utilities/Utilities.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppArchiveIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppBindIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppBookmarkSet.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppByteStreamIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppCodec.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppConstants.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppDataForm.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppDiscoveryIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppElement.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppEntityTimeIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppGlobal.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppIbbIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppJingleIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppLogger.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppMessage.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppMessageCarbonsIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppMucIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppNonSASLAuth.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppPingIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppPresence.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppPubSubIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppReachAddress.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppRegisterIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppResultSet.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppRosterIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppRpcIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppRtpChannel.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSasl.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSessionIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSimpleArchiveIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSimpleArchivePreferenceIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSocks.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStanza.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStream.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStreamFeatures.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStreamInitiationIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStreamManagement.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStun.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppUtils.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppVCardIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppVersionIq.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/qdnslookup.cpp) \
        $$quote($$BASEDIR/src/qxmpp/base/qdnslookup_stub.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppArchiveManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppBookmarkManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppCallManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppClient.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppClientExtension.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppConfiguration.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppDiscoveryManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppEntityTimeManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppInvokable.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppMessageReceiptManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppMucManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppOutgoingClient.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppPEPManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppRemoteMethod.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppRosterManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppRpcManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppSimpleArchiveManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppTransferManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppVCardManager.cpp) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppVersionManager.cpp) \
        $$quote($$BASEDIR/src/service.cpp) \
        $$quote($$BASEDIR/src/serviceXX.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/HubAccount.hpp) \
        $$quote($$BASEDIR/src/HubCache.hpp) \
        $$quote($$BASEDIR/src/TestAccount.hpp) \
        $$quote($$BASEDIR/src/UDSUtil.hpp) \
        $$quote($$BASEDIR/src/Utilities/Utilities.hpp) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppArchiveIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppBindIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppBookmarkSet.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppByteStreamIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppCodec_p.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppConstants.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppDataForm.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppDiscoveryIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppElement.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppEntityTimeIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppGlobal.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppIbbIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppJingleIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppLogger.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppMessage.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppMessageCarbonsIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppMucIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppNonSASLAuth.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppPingIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppPresence.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppPubSubIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppReachAddress.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppRegisterIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppResultSet.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppRosterIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppRpcIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppRtpChannel.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSasl_p.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSessionIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSimpleArchiveIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSimpleArchivePreferenceIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppSocks.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStanza.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStream.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStreamFeatures.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStreamInitiationIq_p.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStreamManagement.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppStun.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppUtils.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppVCardIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/QXmppVersionIq.h) \
        $$quote($$BASEDIR/src/qxmpp/base/qdnslookup.h) \
        $$quote($$BASEDIR/src/qxmpp/base/qdnslookup_p.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppArchiveManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppBookmarkManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppCallManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppClient.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppClientExtension.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppConfiguration.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppDiscoveryManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppEntityTimeManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppInvokable.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppMessageReceiptManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppMucManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppOutgoingClient.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppPEPManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppRemoteMethod.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppRosterManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppRpcManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppSimpleArchiveManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppTransferManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppTransferManager_p.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppVCardManager.h) \
        $$quote($$BASEDIR/src/qxmpp/client/QXmppVersionManager.h) \
        $$quote($$BASEDIR/src/service.hpp) \
        $$quote($$BASEDIR/src/serviceXX.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/Utilities/*.c) \
        $$quote($$BASEDIR/../src/Utilities/*.c++) \
        $$quote($$BASEDIR/../src/Utilities/*.cc) \
        $$quote($$BASEDIR/../src/Utilities/*.cpp) \
        $$quote($$BASEDIR/../src/Utilities/*.cxx) \
        $$quote($$BASEDIR/../src/qxmpp/*.c) \
        $$quote($$BASEDIR/../src/qxmpp/*.c++) \
        $$quote($$BASEDIR/../src/qxmpp/*.cc) \
        $$quote($$BASEDIR/../src/qxmpp/*.cpp) \
        $$quote($$BASEDIR/../src/qxmpp/*.cxx) \
        $$quote($$BASEDIR/../src/qxmpp/base/*.c) \
        $$quote($$BASEDIR/../src/qxmpp/base/*.c++) \
        $$quote($$BASEDIR/../src/qxmpp/base/*.cc) \
        $$quote($$BASEDIR/../src/qxmpp/base/*.cpp) \
        $$quote($$BASEDIR/../src/qxmpp/base/*.cxx) \
        $$quote($$BASEDIR/../src/qxmpp/client/*.c) \
        $$quote($$BASEDIR/../src/qxmpp/client/*.c++) \
        $$quote($$BASEDIR/../src/qxmpp/client/*.cc) \
        $$quote($$BASEDIR/../src/qxmpp/client/*.cpp) \
        $$quote($$BASEDIR/../src/qxmpp/client/*.cxx)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
